### ISSUE TITLE
Overlapped classes

### ISSUE THREAD

**Issue by kaiyingshan** [awesome-schedule/Awesome-SchedulAR#1]
Generated schedule has course overlap which should be filtered by the algorithm.
![issue1](https://user-images.githubusercontent.com/43483881/54869844-cc430480-4d74-11e9-8f22-32ed6901fafe.png)
CS 4774 on Tuesday is covered by PHYS 2419.

**Comment by OAHC2022** [comment]
I think I have fixed this problem @hanzhi713
