### ISSUE TITLE
Variance Sorting Malfunctioning

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#11]
It seems that one schedule with less variance has been placed after the one with more variance.
![issue6_variance](https://user-images.githubusercontent.com/43483555/56095949-f1c4b900-5eaf-11e9-80df-26f8f6d79552.png)

![issue6_variance2](https://user-images.githubusercontent.com/43483555/56095950-f2f5e600-5eaf-11e9-8e9c-e895560bde47.png)
The above two seems to have less variance then the below two.

![issue6_variance3](https://user-images.githubusercontent.com/43483555/56095951-f38e7c80-5eaf-11e9-8106-64888e7e0852.png)

![issue6_variance4](https://user-images.githubusercontent.com/43483555/56095952-f4bfa980-5eaf-11e9-8008-47b928d5eaff.png)

**Comment by hanzhi713** [comment]
I believe the reason behind it is that you've selected multiple indicators and used the combined sorting mode. Please check.

**Comment by OAHC2022** [comment]
There are no other indicator, but I checked the time again. It sorting is correct. It is just the display which tricked me.
