### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#12]
When I change the Schedule Display setting: Schedule Start to 9:00 AM. The display shows a bug as shown below:
![issue7display](https://user-images.githubusercontent.com/43483555/56248903-d6a4a580-6077-11e9-8102-fb0d02aa33ce.png)

**Comment by hanzhi713** [comment]
Should be fixed at 77d0a9e3041e124d463e7152e3cf97ca1cd6463d
