### ISSUE TITLE
Loading Semester Data Problem

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#13]
When I change to Semester 2019 Spring to view the courses, it works fine. But when I change back to 2019 Fall, it became stuck in loading loop. I have to clear cache and restart the website in order for the website to work.
![issue8Loading_Data](https://user-images.githubusercontent.com/43483555/56252869-fd6ad800-6087-11e9-9177-381659562f7c.png)

**Comment by hanzhi713** [comment]
Cannot be reproduced.
