### ISSUE TITLE
Class List Issue

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#15]
This is a general issue. Reproduce the issue as follows: select a class by its section. In the selected tab, click on that class. The class will disappear. Please fix
![issue_10classissue](https://user-images.githubusercontent.com/43483555/56402276-9a657680-622a-11e9-9024-e6ee29d02f3e.png)

**Comment by hanzhi713** [comment]
Fixed. Closed.
