### ISSUE TITLE
Variance seems wrong

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#16]
It seems that the variance feature ordering might be reversed. The variance of the figure 1 is larger than the variance of figure 2
<img width="895" alt="1" src="https://user-images.githubusercontent.com/43483555/56461639-2939d680-6384-11e9-983e-a56fb5cf8b78.png">
<img width="886" alt="2" src="https://user-images.githubusercontent.com/43483555/56461640-2a6b0380-6384-11e9-8fcb-fd021714a5d8.png">

**Comment by hanzhi713** [comment]
Can you give me the class list?

**Comment by OAHC2022** [comment]
Here is the list
![image](https://user-images.githubusercontent.com/43483555/56462812-796e6400-6397-11e9-8c7f-ea6547e39090.png)

**Comment by hanzhi713** [comment]
I got the opposite result, which is correct. Don't know how to duplicate.

**Comment by hanzhi713** [comment]
Actually, it turns out that they have the same variance.
