### ISSUE TITLE
报错信息看不懂

### ISSUE THREAD

**Issue by kitkat0001** [awesome-schedule/Awesome-SchedulAR#17]
![图片](https://user-images.githubusercontent.com/49820611/56461630-0b6c7180-6384-11e9-83e8-2e4c849b32f8.png)
Maybe explain "t[0] is undefined" to a more specific issue, make it easier so that people will know which part is wrong, then fix it.

**Comment by kaiyingshan** [comment]
Please give us more details on how this error message appeared, e.g. I changed xxx setting, added xxx class, and clicked the generate button, then this error message appeared.

**Comment by hanzhi713** [comment]
Strange error messages usually occur when there is a bug or an unhandled case in our code. We need more information in order to reproduce and address the issue.

**Comment by hanzhi713** [comment]
Seem to be a spelling mistake which is fixed at 1896670e7fb3e005018270ec8d0dd57b578975a4

**Comment by hanzhi713** [comment]
Issue no longer active. Closed
