### ISSUE TITLE
Reverse Lunchtime

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#19]
The reverse button seems not working
![issue_reverse](https://user-images.githubusercontent.com/43483555/56462469-9011bc80-6391-11e9-9504-22bca9d5eee2.png)
![issue_reverse2](https://user-images.githubusercontent.com/43483555/56462470-9011bc80-6391-11e9-9d2e-c9af6143e2e3.png)

**Comment by hanzhi713** [comment]
This is not a bug. Only the schedules that have an overlap **greater than an hour per day** with the lunch period, defined as the time between 11:00 to 14:00, will be penalized and sorted to the back.
