### ISSUE TITLE
Generated Schedule disappearing

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#2]
When I choose setup the following filter constraint and submit the following courses, the scheduler tells me it successfully generates the schedule, but nothing appears on the screen. I believe the cause is that the ScheduleGenerator returns an empty list.

Filter setup:
![FilterSetup](https://user-images.githubusercontent.com/43483555/55244830-50cfd000-5218-11e9-9297-be4c41b9a002.png)

Courses selected:
![ClassSelected](https://user-images.githubusercontent.com/43483555/55245533-b7a1b900-5219-11e9-9aa4-58fa313ccbfd.png)

Result:
![Result](https://user-images.githubusercontent.com/43483555/55245655-f0419280-5219-11e9-988e-ae08b3239fd5.png)

Also, my selected classes disappeared. One last thing: what does *Generated Schedule: 3* mean?

**Comment by OAHC2022** [comment]
> When I choose setup the following filter constraint and submit the following courses, the scheduler tells me it successfully generates the schedule, but nothing appears on the screen. I believe the cause is that the ScheduleGenerator returns an empty list.
> 
> Filter setup:
> ![FilterSetup](https://user-images.githubusercontent.com/43483555/55244830-50cfd000-5218-11e9-9297-be4c41b9a002.png)
> 
> Courses selected:
> ![ClassSelected](https://user-images.githubusercontent.com/43483555/55245533-b7a1b900-5219-11e9-9aa4-58fa313ccbfd.png)
> 
> Result:
> ![Result](https://user-images.githubusercontent.com/43483555/55245655-f0419280-5219-11e9-988e-ae08b3239fd5.png)
> 
> Also, my selected classes disappeared. One last thing: what does _Generated Schedule: 8_ mean?

**Comment by hanzhi713** [comment]
Fix at 0f302d72a9f15c9970fb4f6ec49af129efe7ded6. Closed.
