### ISSUE TITLE
ICalendar Sync with Google Calendar

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#20]
When I made this schedule and import in google calendar, it seems to have bug. 
![issue](https://user-images.githubusercontent.com/43483555/56625597-07528500-660c-11e9-986b-05bfc26eafa2.png)
![issue1](https://user-images.githubusercontent.com/43483555/56625598-07528500-660c-11e9-8556-709dbe956d85.png)

Ask me to send you the icalendar file and json file if needed

**Comment by kaiyingshan** [comment]
It seems like the problem is due to multi-section of APMA 2130. Fixed at 821a17cbcae5ec75f5a17134dee3b4ba1a6de58a.
