### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#21]
When I try to select EDHS8700 Lecture. It shows bug as follows
![issue0](https://user-images.githubusercontent.com/43483555/56746132-97e2af80-6749-11e9-935d-67323c7ec887.png)

**Comment by hanzhi713** [comment]
Fixed at 631c17113a553188a7ff0c5caa3b4b053be59022. Now TBAs are not rendered anymore.
