### ISSUE TITLE
Rendering Issue?

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#22]
When I select advanced Scuba Diving, there is a rendering issue
![issue2](https://user-images.githubusercontent.com/43483555/56747410-e98c3980-674b-11e9-8506-c9c083d79fca.png)

**Comment by hanzhi713** [comment]
12:00AM to 12:00AM are you series?

**Comment by hanzhi713** [comment]
After 631c17113a553188a7ff0c5caa3b4b053be59022, no TBAs are rendered anymore.
