### ISSUE TITLE
Section Error

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#28]
Since this class is a weird one, it is difficult to tell what went wrong. From the screen shot on the left, PHAR 9995 has one section to choose on top but it clearly has more than one section in the edit class. 
![Screenshot from 2019-05-26 23-30-23](https://user-images.githubusercontent.com/43483555/58393806-58d8a000-800e-11e9-8b64-0ee41e5be953.png)

**Comment by hanzhi713** [comment]
What's your search query

**Comment by hanzhi713** [comment]
Only sections that match the search query will be shown. This probably needs some explanation in the documentation.
