### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#31]
As the following pictures show, I did the following steps:
1. I put all the classes (including CS 1110 lab and lecture) and generate them: it worked fine
2. I add a filter for no class on friday, it tells me there is a conflict
3. I delete the CS 1110 and try to generate again, it tells me there is still a conflict
![cs1110](https://user-images.githubusercontent.com/43483555/59959891-75d98500-948d-11e9-9695-0994c26f01b2.png)

![cs1110_2](https://user-images.githubusercontent.com/43483555/59959890-74a85800-948d-11e9-9e96-872a68617ac4.png)

**Comment by hanzhi713** [comment]
Fixed.
