### ISSUE TITLE
Rendering at 8:00 AM with Variance and Compactness

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#4]
* Item The Variance of rendering is off, shown as below:
![Issue3_rendering](https://user-images.githubusercontent.com/43483555/55269292-f8282380-5267-11e9-80c3-6d1a34174751.png)

* Item The Variance seems to be more compact than the Compactness
![Issue3_Compactness](https://user-images.githubusercontent.com/43483555/55269333-6c62c700-5268-11e9-865a-a99ef5f386ea.png)

**Comment by hanzhi713** [comment]
This is a bug of the schedule rendering @kaiyingshan. You should notice that the econ discussion is 8 PM and is not 8 AM. Therefore, it is actually very far away from other classes.
