### ISSUE TITLE
Increased Loading Time

### ISSUE THREAD

**Issue by OAHC2022** [awesome-schedule/Awesome-SchedulAR#7]
Now when I open the website, it takes much longer to load the data than before
![issue_4](https://user-images.githubusercontent.com/43483555/55413417-4757a800-5537-11e9-8393-6fcb873fff12.png)

**Comment by hanzhi713** [comment]
This is the expected behavior when the internet is slow.

**Comment by hanzhi713** [comment]
We used the `csv-parse` library which is designed for NodeJS, not for the browser. Now I replaced it with `papaparse`, which is faster on the browser. 

Replaced at 0fe3f4c519be2e427e909b38c4972bae8acdf946
