### ISSUE TITLE
Filter doesn't work accordingly

### ISSUE THREAD

**Issue by Elena6918** [awesome-schedule/Awesome-SchedulAR#9]
When I fill the filter with 09:00 - 20:00 and hit generate button, the pop out message says there's no matching class of CS 2150 of the given filter. My five-class schedule suddenly change to two classes after I apply this filter as well.
<img width="1227" alt="Screen Shot 2019-04-03 at 10 43 33" src="https://user-images.githubusercontent.com/35663865/55488157-7f292300-55fd-11e9-8e84-c95d68614353.png">
<img width="1219" alt="Screen Shot 2019-04-03 at 10 43 44" src="https://user-images.githubusercontent.com/35663865/55488175-88b28b00-55fd-11e9-8f82-1a29d6948edc.png">

**Comment by hanzhi713** [comment]
The filter is NO CLASS TIME. That is, the time that you DON'T want any classes.

**Comment by Elena6918** [comment]
Thanks for the clarificarion.
